name: simver
permissions: { id-token: write, contents: write, pull-requests: read }
on:
    workflow_dispatch:
    push:
        branches: [main]
    pull_request:
        types: [opened, synchronize, reopened, closed]
jobs:
    simver:
        uses: walteh/simver/.github/workflows/simver.yaml@v0.23.0
        secrets: inherit
